{{- if and .Values.sparkConnect.enabled .Values.ingress.enabled .Values.sparkConnect.sparkui.hostname }}
{{- $fullName := include "library-chart.fullname" . -}}
{{- if eq (.Values.ingress.ingressClassName | default "") "apisix" }}
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: {{ $fullName }}-spark-connect-ui
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: spark-connect
spec:
  http:
    - name: {{ $fullName }}-spark-ui
      match:
        hosts:
          - {{ .Values.sparkConnect.sparkui.hostname | quote }}
        paths:
          - "/*"
      plugin_config_name: global-sso-policy
      plugin_config_namespace: ingress-apisix
      backends:
        - serviceName: {{ $fullName }}-spark-connect
          servicePort: 4040
{{- if and .Values.ingress.useTlsSecret (ne .Values.ingress.tlsSecretName "") }}
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: {{ $fullName }}-spark-connect-tls
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: spark-connect
spec:
  hosts:
    - {{ .Values.sparkConnect.sparkui.hostname | quote }}
  secret:
    name: {{ .Values.ingress.tlsSecretName }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- else }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-spark-connect-ui
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: spark-connect
  annotations:
    {{- include "library-chart.ingress.annotations" . | nindent 4 }}
spec:
  {{- if and .Values.ingress.ingressClassName (eq "true" (include "library-chart.ingress.supportsIngressClassname" .)) }}
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.sparkConnect.sparkui.hostname | quote }}
      {{- if and .Values.ingress.useTlsSecret (ne .Values.ingress.tlsSecretName "") }}
      secretName: {{ .Values.ingress.tlsSecretName }}
      {{- else if or .Values.ingress.useCertManager .Values.ingress.useTlsSecret }}
      secretName: tls-cert-{{ $fullName }}
      {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.sparkConnect.sparkui.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-spark-connect
                port:
                  number: 4040
{{- end }}
{{- end }}
