apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "database-restore.fullname" . }}-data
  labels:
    {{- include "database-restore.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.volume.storageClass }}
  resources:
    requests:
      storage: {{ .Values.volume.size }}
  dataSource:
    name: {{ include "database-restore.fullname" . }}-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
