apiVersion: v1
kind: Secret
metadata:
  name: {{ include "database-restore.fullname" . }}-sa
  labels:
    {{- include "database-restore.labels" . | nindent 4 }}
type: Opaque
stringData:
  sa-password: {{ .Values.mssql.saPassword | quote }}
