{{- if .Values.discovery.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "database-restore.fullname" . }}-discovery
  labels:
    {{- include "database-restore.labels" . | nindent 4 }}
  annotations:
    onyxia/discovery: "mssql"
data:
  mssql-service: {{ printf "%s.%s.svc.cluster.local" (include "database-restore.fullname" .) .Release.Namespace | b64enc | quote }}
  mssql-port: {{ .Values.mssql.port | toString | b64enc | quote }}
  mssql-database: {{ .Values.database.name | b64enc | quote }}
  mssql-username: {{ .Values.reader.username | b64enc | quote }}
  password: {{ .Values.reader.password | b64enc | quote }}
{{- end }}
