apiVersion: v1
kind: Secret
metadata:
  name: {{ include "library-chart.fullname" . }}-shiro
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
stringData:
  shiro.ini: |
    [users]
    {{ .Values.environment.user }} = {{ .Values.security.password }}, admin

    [main]
    sessionManager = org.apache.shiro.web.session.mgt.DefaultWebSessionManager
    securityManager.sessionManager = $sessionManager
    securityManager.sessionManager.globalSessionTimeout = 86400000
    shiro.loginUrl = /api/login

    [roles]
    admin = *

    [urls]
    /api/version = anon
    /api/cluster/address = anon
    /api/interpreter/setting/restart/** = authc
    /api/interpreter/** = authc, roles[admin]
    /api/notebook-repositories/** = authc, roles[admin]
    /api/configurations/** = authc, roles[admin]
    /api/credential/** = authc, roles[admin]
    /** = authc
