{{- if .Values.sparkConnect.enabled }}
{{- $fullName := include "library-chart.fullname" . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $fullName }}-spark-connect
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: spark-connect
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "list", "watch", "delete", "deletecollection"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "get", "list", "watch", "delete", "deletecollection"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "get", "list", "watch", "delete", "deletecollection"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["create", "get", "list", "watch", "delete", "deletecollection"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $fullName }}-spark-connect
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: spark-connect
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $fullName }}-spark-connect
subjects:
  - kind: ServiceAccount
    name: {{ include "library-chart.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
